// Bài 11. Viết chương trình đặt chỗ ngồi cho 1 máy bay.Máy bay có 13 hàng ghế, 
//         mỗi hàng có 6 ghế.Hàng 1 và 2 là hạng thương gia, hàng 3 đến 7 là hạng phổ thông, 
//         hàng 8 trở đi là hạng tiết kiệm.Chương trình in ra bảng đặt chỗ ngồi có dạng như sau:
//         A B C D E F 
// HANG 1  * * x * x x
// HANG 2  * x * x * x
// ...
// HANG 13 * * * * x *
// (*: chỗ còn trống, x: chỗ đã đặt)
// Chương trình yêu cầu người dùng nhập vào loại vé (thương gia, phổ thông hay tiết kiệm) và
// chỗ ngồi muốn đặt. Chương trình kiểm tra và in thông báo thích hợp, đồng thời có menu cho
// phép người dùng lựa chọn.